spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

media_player:
#   - platform: onkyo
#     host: 10.7.11.49
#     name: lounge amplifier
#     sources:
#       bd: "Nvidia Shield"
