- id: '1669822480931'
  alias: Auto Away Mode
  description: Set Away Mode
  trigger:
  - platform: state
    entity_id:
    - person.simon
    - person.frieda
    to: not_home
  condition:
  - condition: state
    entity_id: person.simon
    state: not_home
  - condition: state
    entity_id: person.frieda
    state: not_home
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.away_mode
  mode: single
- id: '1669823881405'
  alias: Toggle Vallox Fan Speeds
  description: based on away/home
  trigger:
  - platform: state
    entity_id:
    - input_boolean.away_mode
    to: 'on'
  condition: []
  action:
  - type: turn_off
    device_id: 876f56c448cd0842970e0f41e900af55
    entity_id: fan.vallox
    domain: fan
  mode: single
- id: '1671284181167'
  alias: Turn up heating in the morning
  description: sleep > comfort
  trigger:
  - platform: time
    at: 06:00:00
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: comfort
    target:
      entity_id:
      - climate.study
      - climate.lounge
      - climate.bathroommain
      - climate.bathroomguest
      - climate.lounge
      - climate.study
- id: '1671787400393'
  alias: Turn on tablet screens and set URL - new
  description: turn on wallpanel screen when motion detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroomguest
    - binary_sensor.bathroommain
    - binary_sensor.bedroom1
    - binary_sensor.bedroom2
    - binary_sensor.bedroom3
    - binary_sensor.hallwaylarge
    - binary_sensor.hallwaysmall
    - binary_sensor.kitchen
    - binary_sensor.lounge
    - binary_sensor.study
    from: 'off'
    to: 'on'
  condition: []
  action:
  - variables:
      light_sensor: sensor.{{ trigger.to_state.object_id }}_illuminance
      is_bright: '{{ states(light_sensor) | int(0) >= 5 }}'
  - service: mqtt.publish
    data:
      topic_template: wallpanel/{{ trigger.to_state.object_id }}/command
      payload: '{"wake": {{ is_bright }} }'
  mode: single
