# nice config reference: https://github.com/maxl67/home_assistant/blob/main/configuration.yaml
# Loads default set of integrations. Do not remove.

# https://www.home-assistant.io/integrations/default_config/
default_config:

homeassistant:
  name: F17
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  internal_url: !secret internal_url
  country: DE
  currency: EUR
  packages: !include_dir_named ./config/packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
      - 10.7.9.0/24
      trusted_users:
        10.7.9.0/24: 
        - 7dfaf87f809044188ef0fdbe177006c6
      allow_bypass_login: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# include history
history:


# !include filename.yaml is the statement that tells Home Assistant to insert the contents of filename.yaml at that point
# !include_dir_list will return the content of a directory as a list with each file content being an entry in the list.
# !include_dir_named will return the content of a directory as a dictionary which maps filename => content of file.
# !include_dir_merge_list will return the content of a directory as a list by merging all files (which should contain a list) into 1 big list.
# !include_dir_merge_named will return the content of a directory as a dictionary by loading each file and merging it into 1 big dictionary.

# Things that live outside of packages
#automation:     !include_dir_merge_list ./config/automation
#blueprint:      !include_dir_merge_named  ./config/blueprint
# device_tracker: !include_dir_merge_named ./config/device_tracker
# group:          !include_dir_merge_named ./config/group
# input_boolean:  !include_dir_merge_named ./config/input_boolean
# logger:         !include_dir_merge_named ./config/logger
# lovelace:       !include_dir_merge_named ./config/lovelace
# scene:          !include_dir_merge_named ./config/scene
# script:         !include_dir_merge_named ./config/script
# shell_command:  !include_dir_merge_named ./config/shell_command
# switch:         !include_dir_merge_named ./config/switch
# template:       !include_dir_merge_named ./config/template

# My own handmade automations
automation manual: !include_dir_merge_list ./config/automation

# Automations I create in the UI
automation ui: !include automations.yaml

input_number:
  normal_electricity_price:
    name: normal electric price
    initial: 0.26
    min: 0.00
    max: 1.00
    step: 0.01
    mode: box
    unit_of_measurement: EUR/kWh
  heating_electricity_price:
    name: heating electricity price
    initial: 0.47
    min: 0.00
    max: 1.00
    step: 0.01
    mode: box
    unit_of_measurement: EUR/kWh
  cold_water_price:
    name: cold water price
    initial: 3.90
    min: 0.00
    max: 10.00
    step: 0.01
    mode: box
    unit_of_measurement: EUR/m³
  hot_water_price:
    name: hot water price
    initial: 15.00 # approx
    min: 0.00
    max: 99.00
    step: 0.01
    mode: box
    unit_of_measurement: EUR/m³
  water_counter_pulses_per_liter:
    name: water counter pulses per liter
    initial: 400 # approx
    min: 300
    max: 500
    step: 1
    mode: box

# for ventilation amongst other things
input_boolean:
  away_mode:
    name: Away Mode
    
# tablets to keep off at night  
  lounge_dont_turn_on:
    name: dim when dark lounge
    initial: false
  study_dont_turn_on:
    name: dim when dark study
    initial: false
  kitchen_dont_turn_on:
    name: dim when dark kitchen
    initial: false
  hallwaylarge_dont_turn_on:
    name: dim when dark hallwaylarge
    initial: false
  bathroomguest_dont_turn_on:
    name: dim when dark bathroomguest
    initial: false
  bathroommain_dont_turn_on:
    name: dim when dark bathroommain
    initial: false
  bedroom1_dont_turn_on:
    name: dim when dark bedroom1
    initial: true
  bedroom2_dont_turn_on:
    name: dim when dark bedroom2
    initial: true
  bedroom3_dont_turn_on:
    name: dim when dark bedroom3
    initial: true

binary_sensor:
  - platform: group
    name: motion sensors
    entities:
      - binary_sensor.lounge
      - binary_sensor.kitchen
      - binary_sensor.study
      - binary_sensor.hallwaylarge
      - binary_sensor.hallwaysmall
      - binary_sensor.bathroommain
      - binary_sensor.bathroomguest
      - binary_sensor.bedroom1
      - binary_sensor.bedroom2
      - binary_sensor.bedroom3

input_select:
  vacuum_room_select:
    name: Choose a room to clean
    options:
      - Kitchen
      - Study
      - Hallway
      - Cat Toilet Area
      - Bathroom Guest
      - Bathroom Main
      - Bedroom 1
      - Bedroom 2
      - Bedroom 3


logger:
  default: info #critical,fatal,error,warning,warn,info,debug,notset
  logs:
    homeassistant.components.vacuum.xiaomi_miio: info
    miio: error
    custom_components.xiaomi_cloud_map_extractor: error
    # For most debugging needs `xnx.log` and one of `xknx.knx` or `xknx.telegram` are a good choice.
    xknx: info  # sets the level of all loggers
    xknx.log: info  # provides general information (connection, etc.)
    xknx.raw_socket: info  # logs incoming UDP frames in raw hex format
    xknx.knx: info  # logs incoming and outgoing KNX/IP frames at socket level
    xknx.telegram: info  # logs telegrams before they are being processed at device level or sent to an interface
    xknx.state_updater: info  # provides information about the state updater

lovelace:
  mode: storage
  dashboards:
    rooms-dashboard:
      mode: yaml
      title: Rooms
      icon: mdi:door
      show_in_sidebar: true
      filename: config/dashboards/rooms.yaml
    heating-dashboard:
      mode: yaml
      title: HVAC
      icon: mdi:heat-pump
      show_in_sidebar: true
      filename: config/dashboards/hvac.yaml
    music-dashboard:
      mode: yaml
      title: Music
      icon: mdi:music
      show_in_sidebar: true
      filename: config/dashboards/music.yaml
    vacuum-dashboard:
      mode: yaml
      title: Vacuum
      icon: mdi:robot-vacuum
      show_in_sidebar: true
      filename: config/dashboards/vacuum.yaml

vacuum:
  - platform: xiaomi_miio
    name: imagiSuck
