# just shared spaces (no bedrooms)

- id: '1669640825770'
  alias: Turn down heating before bed
  description: ''
  trigger:
  - platform: time
    at: '20:30:00'
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: sleep
    target:
      entity_id:
      - climate.study
      - climate.lounge
      - climate.bathroommain
      - climate.bathroomguest
      - climate.lounge
      - climate.study

- id: '1669641292099'
  alias: heating morning switch on comfort mode
  description: ''
  trigger:
    platform: time
    at: 06:15:00
  action:
  - service: climate.set_preset_mode
    target:
      - climate.study
      - climate.lounge
      - climate.bathroommain
      - climate.bathroomguest
      - climate.lounge
      - climate.study
    data:
      preset_mode: comfort
