- id: switch_to_away_mode
  alias: switch to away mode
  description: based on away/home
  trigger:
    - platform: state
      entity_id:
        - input_boolean.away_mode
      to: "on"
  condition: []
  action:
    - type: turn_off
      service: vallox.set_profile_fan_speed_away
  mode: single
