# wake the sleeping tablets
- id: "wake wallpanel and set url"
  alias: Turn on tablet screens and set URL
  description: turn on wallpanel screen when motion detected
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroomguest_motion
        - binary_sensor.bathroommain_motion
        - binary_sensor.bedroom1_motion
        - binary_sensor.bedroom2_motion
        - binary_sensor.bedroom3_motion
        - binary_sensor.hallwaylarge_motion
        - binary_sensor.hallwaysmall_motion
        - binary_sensor.kitchen_motion
        - binary_sensor.lounge_motion
        - binary_sensor.study_motion
      to: "on" 
  condition: []
  action:
    - service: mqtt.publish
      data:
        topic_template: "wallpanel/{{ trigger.to_state.object_id }}/command"
        payload: '{"wake": true}'
    # - service: mqtt.publish
    #   data:
    #     topic_template: "wallpanel/{{ trigger.to_state.object_id }}/command"
    #     payload: '{"url": "http://ha.imagilan/rooms-dashboard/{{ trigger.to_state.object_id }}"}'
  mode: single
