- id: 'motion_wallpanel_study'
  alias: Turn on Screen
  description: turn on wallpanel screen when motion detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: wallpanel/study/command
      payload: '{"wake": true, "wakeTime": 10}'
  mode: single

- id: 'motion_wallpanel_kitchen'
  alias: Turn on Screen
  description: turn on wallpanel screen when motion detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.kitchen
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: wallpanel/kitchen/command
      payload: '{"wake": true}' 
       # we don't send a wakeTime since this is set with 
       # adb shell settings put system screen_off_timeout 30000
  mode: single
