# wake the sleeping tablets
- id: "wake wallpanel and set url"
  alias: Turn on tablet screens and set URL
  description: turn on wallpanel screen when motion detected
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroomguest
        - binary_sensor.bathroommain
        - binary_sensor.bedroom1
        - binary_sensor.bedroom2
        - binary_sensor.bedroom3
        - binary_sensor.hallwaylarge
        - binary_sensor.hallwaysmall
        - binary_sensor.kitchen
        - binary_sensor.lounge
        - binary_sensor.study
      to: "on" 
  condition: []
  action:
    - service: mqtt.publish
      data:
        topic_template: "wallpanel/{{ trigger.to_state.object_id }}/command"
        payload: '{"wake": true}'
    # - service: mqtt.publish
    #   data:
    #     topic_template: "wallpanel/{{ trigger.to_state.object_id }}/command"
    #     payload: '{"url": "http://ha.imagilan/rooms-dashboard/{{ trigger.to_state.object_id }}"}'
  mode: single
