alias: Turn on/off panels 2
description: 1) When motion detected, and only if brightness >5, turn on turn on wallpanel screen. When motion detected, and brightness <5, turn off panels.
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bathroomguest
      - binary_sensor.bathroommain
      - binary_sensor.bedroom1
      - binary_sensor.bedroom2
      - binary_sensor.bedroom3
      - binary_sensor.hallwaylarge
      - binary_sensor.hallwaysmall
      - binary_sensor.kitchen
      - binary_sensor.lounge
      - binary_sensor.study
    from: "off"
    to: "on"
condition: []
action:
  - variables:
      light_sensor: 'sensor.{{ trigger.to_state.object_id }}_illuminance'
      is_bright: '{{ states(light_sensor) | int(0) >= 5 }}'

  - if: "{{ (sensor.{{ trigger.to_state.object_id }}_illuminance) | int(0) <= 5 }}"
    then:
      - service: mqtt.publish
        data:
          topic_template: wallpanel/{{ trigger.to_state.object_id }}/command
          payload: '{"wake": false}'
    else:
      - service: mqtt.publish
        data:
        topic_template: wallpanel/{{ trigger.to_state.object_id }}/command
        payload: '{"wake": true, "wakeTime": 180}'
mode: single
