mqtt:
  sensor:
    - name: cold water sensor - manual
      icon: mdi:water
      unique_id: test_mqtt_entry
      state_topic: tele/waterlogger/SENSOR
      state_class: total_increasing
      unit_of_measurement: l
      value_template: "{{ (( value_json.COUNTER.C1 ) | float / 400 ) | round(0) }}"

template:
  - sensor:
    - name: cold
      icon: mdi:water
      unique_id: cold_water_m3
      unit_of_measurement: m³
      device_class: water
      state_class: total_increasing
      state: "{{ (states('sensor.waterlogger_counter_c1') | float / 400 / 1000 ) | round(3) }}"
    - name: hot
      icon: mdi:water-thermometer
      unique_id: hot_water_m3
      state: "{{ ( states('sensor.waterlogger_counter_c2' ) | float / 400 / 1000 ) | round(3) }}"
      unit_of_measurement: m³
      device_class: water
      state_class: total_increasing