#id: vacuum
title: imagiSuck
path: vacuum
icon: mdi:robot-vacuum
cards:
  #------------------------------------------------------------
  # Vacuum map card using data from Xiaomi Cloud Map Extractor
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.xiaomi_vacuum_cleaner
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_locked: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
    icons:
      # default icons ersetzen...
      - icon: mdi:brush
        # ..und diese dann unterdrueken
        conditions:
          - entity: sensor.vacuum_cleanmainbrush
            above: 10

  - type: custom:xiaomi-vacuum-map-card
    map_source:
    camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    entity: vacuum.rockrobo_vacuum_v1
    vacuum_platform: default
    map_locked: false
    title: imagiSuck
    two_finger_pan: false
