input_select:
  hvac_mode:
    name: zone mode
    options:
      - "auto"
      - "comfort"
      - "economy"
      - "off"
    icon: mdi:target

sensor:
  - platform: template
    sensors:
      hvac_set_mode:
        value_template: >
         {% set value = states('input_select.hvac_mode') %}
          {% if value == "auto" %}
            {{ 1 | int }}
          {% elif value == "cool" %}
            {{ 3 | int }}
          {% elif value == "fan" %}
            {{ 9 | int }}
          {% elif value == "dry" %}
            {{ 14 | int }}
          {% else %}
            {{ 0 | int }}
          {% endif %}